set_property PACKAGE_PIN W2 [get_ports {input1[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input1[0]}]
set_property PACKAGE_PIN U1 [get_ports {input1[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input1[1]}]
set_property PACKAGE_PIN T1 [get_ports {input1[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input1[2]}]
set_property PACKAGE_PIN R2 [get_ports {input1[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input1[3]}]
set_property PACKAGE_PIN V2 [get_ports {input2[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input2[0]}]
set_property PACKAGE_PIN T3 [get_ports {input2[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input2[1]}]
set_property PACKAGE_PIN T2 [get_ports {input2[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input2[2]}]
set_property PACKAGE_PIN R3 [get_ports {input2[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {input2[3]}]

set_property PACKAGE_PIN V17 [get_ports {select1[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {select1[0]}]
set_property PACKAGE_PIN V16 [get_ports {select1[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {select1[1]}]
set_property PACKAGE_PIN W16 [get_ports {select1[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {select1[2]}]


set_property PACKAGE_PIN L1 [get_ports {result1[3]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {result1[3]}]
set_property PACKAGE_PIN P1 [get_ports {result1[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {result1[2]}]
set_property PACKAGE_PIN N3 [get_ports {result1[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {result1[1]}]
set_property PACKAGE_PIN P3 [get_ports {result1[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {result1[0]}] 